[tg]
token = '7844956846:AAG1qbeUbRCaY5mUAvK4QUuGx6voW5ZO2wQ'
admin_id = 1835906223


[postgres]
database = "posted"
user = "pugach"
password = "qweqwe"
host = "127.0.0.1"
port = 5432

[redis]
host = "127.0.0.1"
port = 6379