"""update posts2

Revision ID: 5cd9962fb436
Revises: 74e20ce5511a
Create Date: 2024-09-24 21:15:33.559206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd9962fb436'
down_revision: Union[str, None] = '74e20ce5511a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
