"""create_tables

Revision ID: c9dabce14bae
Revises: 
Create Date: 2024-09-23 22:11:17.853513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9dabce14bae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('skip_confirm_post', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_channel_id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('channel_username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_channel_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=True),
    sa.Column('media_content_type', sa.Enum('UNKNOWN', 'ANY', 'TEXT', 'ANIMATION', 'AUDIO', 'DOCUMENT', 'PAID_MEDIA', 'PHOTO', 'STICKER', 'STORY', 'VIDEO', 'VIDEO_NOTE', 'VOICE', 'CONTACT', 'DICE', 'GAME', 'POLL', 'VENUE', 'LOCATION', 'NEW_CHAT_MEMBERS', 'LEFT_CHAT_MEMBER', 'NEW_CHAT_TITLE', 'NEW_CHAT_PHOTO', 'DELETE_CHAT_PHOTO', 'GROUP_CHAT_CREATED', 'SUPERGROUP_CHAT_CREATED', 'CHANNEL_CHAT_CREATED', 'MESSAGE_AUTO_DELETE_TIMER_CHANGED', 'MIGRATE_TO_CHAT_ID', 'MIGRATE_FROM_CHAT_ID', 'PINNED_MESSAGE', 'INVOICE', 'SUCCESSFUL_PAYMENT', 'REFUNDED_PAYMENT', 'USERS_SHARED', 'CHAT_SHARED', 'CONNECTED_WEBSITE', 'WRITE_ACCESS_ALLOWED', 'PASSPORT_DATA', 'PROXIMITY_ALERT_TRIGGERED', 'BOOST_ADDED', 'CHAT_BACKGROUND_SET', 'FORUM_TOPIC_CREATED', 'FORUM_TOPIC_EDITED', 'FORUM_TOPIC_CLOSED', 'FORUM_TOPIC_REOPENED', 'GENERAL_FORUM_TOPIC_HIDDEN', 'GENERAL_FORUM_TOPIC_UNHIDDEN', 'GIVEAWAY_CREATED', 'GIVEAWAY', 'GIVEAWAY_WINNERS', 'GIVEAWAY_COMPLETED', 'VIDEO_CHAT_SCHEDULED', 'VIDEO_CHAT_STARTED', 'VIDEO_CHAT_ENDED', 'VIDEO_CHAT_PARTICIPANTS_INVITED', 'WEB_APP_DATA', 'USER_SHARED', name='contenttype'), nullable=True),
    sa.Column('url_buttons', sa.String(), nullable=True),
    sa.Column('emoji_buttons', sa.String(), nullable=True),
    sa.Column('poll_tittle', sa.String(), nullable=True),
    sa.Column('poll_options', sa.String(), nullable=True),
    sa.Column('scheduled', sa.Boolean(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification', sa.Boolean(), nullable=False),
    sa.Column('hide_media', sa.Boolean(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('count_reaction', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['reaction_id'], ['reactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_reactions')
    op.drop_table('reactions')
    op.drop_table('posts')
    op.drop_table('channels')
    op.drop_table('users')
    # ### end Alembic commands ###
