"""add post_type

Revision ID: e09c383389d3
Revises: 5cd9962fb436
Create Date: 2024-09-25 20:09:54.079417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e09c383389d3'
down_revision: Union[str, None] = '5cd9962fb436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

message_type_enum = sa.Enum('poll', 'message', name='messagetype')


def upgrade() -> None:
	# Создать тип Enum в PostgreSQL
	message_type_enum.create(op.get_bind())
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('posts', sa.Column('post_type', message_type_enum, nullable=False))
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('posts', 'post_type')
	# ### end Alembic commands ###
